language: python

python:
    - 2.7
    - 2.6
env:
    - NUMPY_VERSION=1.6.2 
    - NUMPY_VERSION=1.7.0
    
before_install:
   # http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq 
   - sudo apt-get install -qq python-numpy cython libatlas-dev liblapack-dev gfortran
   - sudo apt-get install -qq python-scipy 
   - sudo apt-get install -qq tk8.5
   - sudo apt-get install -qq python-tk
   - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then sudo apt-get install -qq python2.6-tk; fi
   - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install -qq python2.7-tk; fi
   - sudo apt-get build-dep python-matplotlib
   - sudo apt-get install -qq python-matplotlib
install: 
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip install --upgrade "numpy==$NUMPY_VERSION" -q --use-mirrors
   - pip install matplotlib --use-mirrors
   - pip install scipy --use-mirrors
   - python setup.py install # I guess?
script: python setup.py test
